$token = "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJmZWEzYzIzNjgyNmUwNmE5ZDJhZmMwZWJjMzJlMTMwYyIsImFjY2Vzc1J1bGVzIjpbeyJpZCI6InRyYWRpbmctYWNjb3VudC1tYW5hZ2VtZW50LWFwaSIsIm1ldGhvZHMiOlsidHJhZGluZy1hY2NvdW50LW1hbmFnZW1lbnQtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcmVzdC1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcnBjLWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6d3M6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcmVhbC10aW1lLXN0cmVhbWluZy1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOndzOnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJtZXRhc3RhdHMtYXBpIiwibWV0aG9kcyI6WyJtZXRhc3RhdHMtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6InJpc2stbWFuYWdlbWVudC1hcGkiLCJtZXRob2RzIjpbInJpc2stbWFuYWdlbWVudC1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoiY29weWZhY3RvcnktYXBpIiwibWV0aG9kcyI6WyJjb3B5ZmFjdG9yeS1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibXQtbWFuYWdlci1hcGkiLCJtZXRob2RzIjpbIm10LW1hbmFnZXItYXBpOnJlc3Q6ZGVhbGluZzoqOioiLCJtdC1tYW5hZ2VyLWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJiaWxsaW5nLWFwaSIsIm1ldGhvZHMiOlsiYmlsbGluZy1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfV0sImlnbm9yZVJhdGVMaW1pdHMiOmZhbHNlLCJ0b2tlbklkIjoiMjAyMTAyMTMiLCJpbXBlcnNvbmF0ZWQiOmZhbHNlLCJyZWFsVXNlcklkIjoiZmVhM2MyMzY4MjZlMDZhOWQyYWZjMGViYzMyZTEzMGMiLCJpYXQiOjE3NzU3OTEzNTAsImV4cCI6MTc4MzU2NzM1MH0.Mq3AckiYb-F3xa1-0D99s5WtDYy8KXSQlHeIeOs2pRaAjyMBLFToKRuj5i9sqzVZFVbEMFEXOHGZi0l29iNbL7ZRrjeH7T5kkhnLWxDkcoxraqizmlH1l1P8KrdU7RncYhpv0iD1p7vbLREItHdAwa25zGiTKmbgwjwscmrgOLbbYD25WZNBbaAkoVlkqLZTuYFyReaq07fLhPLfrsacWBh3FZ3GcTmDJ3oecC2Bbb4pemYhMBUp8rZrOiuZfOySTVwGmzbmVPXFj5Im0doXC6Afxh6LBDEBCroKEb5-ZGF1Q5qYC5Nk5OBU7tOxhpKFoEDsoKgbiwLAKCu7h73qiEB0ObTkuxL94croYK63GJdN1GebRsAIIFiInYYX9UzEYh2jK501w3N76SaYa1hwnb6lE364eMAcGG7tNlV8LY1Bnd62O-QV7LvXsRC8XCCygUdnzZ_eMuy8hxlwi6NUUJdNmxmgMTapb6Ic0-UYfvQMMGCmcngX6dJwKAY_OMxIPCH_Bcrp49X7l377PwFCZwXapWFVvH1imMmVCvWvxJQWXuWu3sCa3jj1E4m0KY3dbaH9U9TkHD_4LkaCWXaXttmrkhc8HfVSD6dAggZJS7kWnYvTRqPIkQSgDiMU-RmGJFagEXc-7eij49tgm_1uMHvKwj9RXNEII6lWaZr1ya4"

$headers = @{
    "auth-token" = $token
    "Content-Type" = "application/json"
}

$body = @{
    login = "24963323"
    password = "cX`$P02Br"
    name = "ZenPips-Demo-Bridge"
    server = "VantageInternational-Demo"
    platform = "mt5"
    type = "cloud-g2"
} | ConvertTo-Json

try {
    $response = Invoke-RestMethod -Uri "https://mt-provisioning-api-v1.agiliumtrade.agiliumtrade.ai/users/current/accounts" -Method Post -Headers $headers -Body $body
    $response | ConvertTo-Json -Depth 5
} catch {
    Write-Host "Status: $($_.Exception.Response.StatusCode)"
    $reader = [System.IO.StreamReader]::new($_.Exception.Response.GetResponseStream())
    $reader.ReadToEnd()
}
